# Generated by Django 4.2.14 on 2024-08-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_alter_container_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uri',
            field=models.CharField(blank=True, editable=False, max_length=4096, null=True, unique=True),
        ),
    ]
