# Generated by Django 4.2.14 on 2024-08-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_product_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uri',
            new_name='slug',
        ),
    ]
