# Generated by Django 4.2.14 on 2024-09-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='ams.product'),
        ),
    ]
