# Generated by Django 4.2.14 on 2024-09-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_alter_bundle_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.container'),
        ),
    ]
