# Generated by Django 4.2.14 on 2024-09-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bundletype'),
        ('ams', '0009_remove_bundle_element_remove_bundle_step'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('container', 'bundle_type', 'version')},
        ),
    ]
