# Generated by Django 4.2.14 on 2024-11-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bundletype_created_by_and_more'),
        ('ams', '0012_bundle_step'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('container', 'step', 'bundle_type', 'version')},
        ),
    ]
