# Generated by Django 4.2.14 on 2024-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_alter_bundle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
