# Generated by Django 4.2.14 on 2025-01-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bundletype_created_by_and_more'),
        ('ams', '0014_bundle_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('container', 'step', 'element', 'data_type', 'lod', 'layer', 'version', 'extension')},
        ),
    ]
